name: CI

on:
  push:
    branches: [master, main, "frontend/**", "backend/**", "feature/**","fix/**"]
  pull_request:
    branches: [master, main]

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Audit dependencies
        run: npm audit --audit-level=critical

      - name: Backend tests (Jest)
        run: npm test

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Lint frontend (ESLint)
        run: npm run lint

      - name: Frontend unit tests (Vitest)
        run: npm test

      - name: Build frontend (Vite)
        run: npm run build